## Assignment 2, 22-Queen Programming

Your homework must be implemented in this Notebook file. 
You can add as many cells as you want. However, you are not allowed to touch the code below the line "=============".


In [49]:
import copy
import numpy as np
size = 22
solutions = []
locations = []

def setBoard():
    gBoard = [0]*size
    for x in range(size):
        gBoard[x] = [0]*size
    return gBoard

def checkN(board, oRow, oCol):
    for row in range(oRow):
            if (board[row][oCol] == 1):
                return False
    return True
def checkW(board, oRow, oCol):
    for col in range(oCol):
        if (board[oRow][col] == 1):
            return False
    return True
def checkNW(board, oRow, oCol):
    row, col = oRow, oCol
    while (row >= 0) & (col>=0):
        if board[row][col] == 1:
            return False
        row -= 1
        col -= 1
    return True
def checkSW(board, oRow, oCol):
    row, col = oRow, oCol
    while (row < size) & (col >= 0):
        if board[row][col] == 1:
            return False
        row += 1
        col -= 1
    return True

def isSafe(board, oRow, oCol):
    if(checkN(board, oRow, oCol)):
        if(checkW(board, oRow, oCol)):
            if(checkNW(board, oRow, oCol)):
                if(checkSW(board, oRow, oCol)):
                    return True
    else: 
        return False
    
    

def solve(board, c):
    if len(solutions) == 5:
        return
    if c >= size:
        return
    for row in range(size):
        if isSafe(board, row, c):
            board[row][c] = 1 #assign queen to location
            if c == size - 1:
                solutions.append(copy.deepcopy(board))
                board[row][c] = 0
                return
            solve(board, c+1)
            board[row][c] = 0
def locate(board):
    del locations[:]
    for row in range(size):
        for col in range(size):
            if board[row][col] == 1:
                locations.append([row, col])

def printLocations(solutionLocations, file):
    for i in range(len(solutionLocations)):
        if i == 11:
            file.write("\n")
        file.write(str(solutionLocations[i]))

def print_result( result ):
    file = open("result.txt", "w")
    for i in range(len(solutions)):
        #file.write(np.matrix(solutions[i]))
        file.write("\n")
        locate(solutions[i])
        printLocations(locations, file)
        file.write("\n")
    
    file.close()
    print("file closed")
                



board = setBoard()
solve(board, 0)
solutions.reverse()
for i in range(len(solutions)):
    print(np.matrix(solutions[i]))
    locate(solutions[i])
    print(np.matrix(locations))
    #printLocations(locations)
    print("\n")
    

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0

You can insert as many cells as you want above
You are not Allowed to modify the code below this line.
===============================

In [50]:
#you need to implement print_result function to print out the result according to the required format
result = 0
print_result( result )

file closed



The output format should be as follows. You only need to give 4 solutions in the following format.
Example Output for 4-queens Problem. Each pair of values represents the position of a queen (row, column)
(0,1) (1,3) (2,0) (3,2)
(0,2) (1,0) (2,3) (3,1)


